baseURL = "https://srxavi.me/"
languageCode = "en-us"
title = "srxavi"
theme = "pulp"

[markup.goldmark.renderer]
    unsafe = true # Allow user HTML tags

[params]
    author = "Xavi Francisco"
    description = """
    <code>[love(passion) for passion in ('Python', 'Free software', 'Privacy', 'Human Rights')]</code>
    """
    keywords = "blog,developer,personal"
    avatar = "avatar.png"

    publicationYear = "2022"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    hidecredits = false
    hidecopyright = false

    inverted = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/srxavi"
    weight = 10

[[menu.main]]
    identifier = "gitlab"
    pre = "<i class='fab fa-gitlab fa-lg'></i>"
    url = "https://gitlab.com/srxavi/"
    weight = 20

[[menu.main]]
    identifier = "mastodon"
    pre = "<i class='fab fa-mastodon fa-lg'></i>"
    url = "https://social.srxavi.me/@xavi"
    weight = 30

[[menu.main]]
    identifier = "linkedin"
    pre = "<i class='fab fa-linkedin fa-lg'></i>"    
    url = "https://www.linkedin.com/in/xavifrancisco/"
    weight = 40
